#include "Parsing.h"
#include <QJsonDocument>
#include <QJsonArray>
#include <QJsonObject>
#include <QXmlStreamReader>
#include <QRegularExpression>
static UniverseRecord mk(const QString&s,const QString&id,const QString&name,const QString&cat,double ra,double dec,double dist,double rad,double mag,bool hd,bool hr,bool hm){ UniverseRecord r; r.source=s;r.id=id;r.name=name;r.category=cat;r.raDeg=ra;r.decDeg=dec;r.distanceLy=dist;r.radiusKm=rad;r.magnitude=mag;r.distanceKnown=hd;r.radiusKnown=hr;r.magnitudeKnown=hm; return r; }
QVector<UniverseRecord> parseJsonArrayRecords(const QByteArray &json, const QString &source){ QVector<UniverseRecord> out; auto doc=QJsonDocument::fromJson(json); if(!doc.isArray()) return out; for(auto v:doc.array()){ auto o=v.toObject(); auto id=o.value("id").toString(o.value("pl_name").toString("unknown")); auto name=o.value("name").toString(o.value("pl_name").toString(id)); auto cat=o.contains("pl_name") ? "Exoplanet" : "Astronomical Object"; auto ra=o.value("ra").toDouble(o.value("ra_deg").toDouble(-1)); auto dec=o.value("dec").toDouble(o.value("dec_deg").toDouble(-1)); auto dist=o.value("sy_dist").toDouble(o.value("distance_ly").toDouble(-1)); auto rad=o.value("st_rad").toDouble(o.value("pl_radj").toDouble(-1)); auto mag=o.value("sy_vmag").toDouble(o.value("magnitude").toDouble(99)); out.push_back(mk(source,id,name,cat,ra,dec,dist,rad,mag,dist>0,rad>0,mag<98)); } return out; }
QVector<UniverseRecord> parseVOTable(const QByteArray &xml, const QString &source){ QVector<UniverseRecord> out; QXmlStreamReader xr(xml); QStringList fields,row; bool in=false; auto idx=[&](QStringList keys){ for(auto &k:keys){ int i=fields.indexOf(k); if(i>=0) return i; } return -1; }; while(!xr.atEnd()){ xr.readNext(); if(xr.isStartElement()){ auto n=xr.name().toString(); if(n=="FIELD") fields << xr.attributes().value("name").toString(); else if(n=="TABLEDATA") in=true; else if(in && n=="TR") row.clear(); else if(in && n=="TD") row << xr.readElementText(); } else if(xr.isEndElement() && xr.name()=="TR" && !row.isEmpty()){ int rai=idx({"ra","RA","RA_ICRS"}), deci=idx({"dec","DEC","DEC_ICRS"}), namei=idx({"main_id","designation","name","source_id"}), magi=idx({"phot_g_mean_mag","mag","Gmag"}); bool okRa=false, okDec=false, okMag=false; double ra=rai>=0&&rai<row.size()?row[rai].toDouble(&okRa):0.0; double dec=deci>=0&&deci<row.size()?row[deci].toDouble(&okDec):0.0; double mag=magi>=0&&magi<row.size()?row[magi].toDouble(&okMag):99.0; if(!okRa||!okDec) continue; QString name=namei>=0&&namei<row.size()?row[namei]:"Gaia Source"; out.push_back(mk(source,name,name,"Star",ra,dec,-1,-1,mag,false,false,okMag)); } } return out; }
QVector<UniverseRecord> parseXmlRecords(const QByteArray &xml, const QString &source){ QVector<UniverseRecord> out; QXmlStreamReader xr(xml); QString id,name; double ra=0,dec=0,dist=-1,rad=-1,mag=99; bool hRa=false,hDec=false; while(!xr.atEnd()){ xr.readNext(); if(xr.isStartElement()){ auto n=xr.name().toString().toLower(); if(n=="objname"||n=="name") name=xr.readElementText(); else if(n=="objid"||n=="id") id=xr.readElementText(); else if(n=="ra"){ ra=xr.readElementText().toDouble(); hRa=true; } else if(n=="dec"){ dec=xr.readElementText().toDouble(); hDec=true; } else if(n=="distance") dist=xr.readElementText().toDouble(); else if(n=="radius") rad=xr.readElementText().toDouble(); else if(n=="mag"||n=="magnitude") mag=xr.readElementText().toDouble(); } if(xr.isEndElement() && xr.name().toString().toLower()=="object"){ if(hRa && hDec){ QString finalName=name.isEmpty() ? (id.isEmpty()?"Object":id) : name; out.push_back(mk(source,id.isEmpty()?finalName:id,finalName,"Astronomical Object",ra,dec,dist,rad,mag,dist>0,rad>0,mag<98)); } id.clear(); name.clear(); ra=dec=0; dist=-1; rad=-1; mag=99; hRa=hDec=false; } } return out; }
QVector<UniverseRecord> parseHtmlFallback(const QByteArray &html, const QString &source){ QVector<UniverseRecord> out; QString s=QString::fromUtf8(html); QRegularExpression titleRe(R"(<title[^>]*>([^<]+)</title>)", QRegularExpression::CaseInsensitiveOption); QRegularExpression raRe(R"((?:\bRA\b|\bra\b)[^0-9+\-]*([+\-]?[0-9]{1,3}(?:\.[0-9]+)?))"); QRegularExpression decRe(R"((?:\bDEC\b|\bDec\b)[^0-9+\-]*([+\-]?[0-9]{1,3}(?:\.[0-9]+)?))"); QString title="Trusted Object"; auto tm=titleRe.match(s); if(tm.hasMatch()) title=tm.captured(1).trimmed(); double ra=0.0, dec=0.0; auto rm=raRe.match(s); if(rm.hasMatch()) ra=rm.captured(1).toDouble(); auto dm=decRe.match(s); if(dm.hasMatch()) dec=dm.captured(1).toDouble(); out.push_back(mk(source,title,title,"Astronomical Object",ra,dec,-1,-1,99.0,false,false,false)); return out; }
